### ISSUE TITLE
App crashes while developing using Flutter "hot reload" only on Android

### ISSUE THREAD

**Issue by luuklelifeld** [ko2ic/flutter_google_ad_manager#31]
Note: This error occurs in the example app as well as my own implementation of this package

In my own application, this banner is shown in the main screen that's loaded when you open the app. When I'm developing, more than half of the startups I do crashes the app. At the same time, when an ad is loaded in the widget tree of my app (or the example app for that matter), and I use Flutter's "hot reload" function, the app crashes as well. These crashes no longer occur when I don't load in any ads.

This error does not occur on iOS.

Error message:

```
Initializing hot reload...                                             ⣻E/flutter ( 8314): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.AbstractMethodError: abstract method "void io.flutter.plugin.platform.PlatformView.onInputConnectionLocked()"
E/flutter ( 8314): 	at io.flutter.plugin.platform.VirtualDisplayController.onInputConnectionLocked(VirtualDisplayController.java:166)
E/flutter ( 8314): 	at io.flutter.plugin.platform.PlatformViewsController.lockInputConnection(PlatformViewsController.java:370)
E/flutter ( 8314): 	at io.flutter.plugin.platform.PlatformViewsController.access$1000(PlatformViewsController.java:36)
E/flutter ( 8314): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:165)
E/flutter ( 8314): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:120)
E/flutter ( 8314): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:57)
E/flutter ( 8314): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter ( 8314): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter ( 8314): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter ( 8314): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8314): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 8314): 	at android.os.Looper.loop(Looper.java:174)
E/flutter ( 8314): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 8314): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 8314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 8314): 
F/flutter ( 8314): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
F/libc    ( 8314): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 8314 (dmanagerexample), pid 8314 (dmanagerexample)
        
Reloaded 0 of 476 libraries in 224ms.
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2019-11-21 16:18:21+0100
pid: 8314, tid: 8314, name: dmanagerexample  >>> com.ko2ic.fluttergoogleadmanagerexample <<<
uid: 10144
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
'
    eax 00000000  ebx 0000207a  ecx 0000207a  edx 00000006
    edi ebf8733e  esi ffb96cd0
    ebp ee702ad0  esp ffb96c78  eip ee702ad9
backtrace:
      #00 pc 00000ad9  [vdso] (__kernel_vsyscall+9)
      #01 pc 00092328  /apex/com.android.runtime/lib/bionic/libc.so (syscall+40) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #02 pc 000ad651  /apex/com.android.runtime/lib/bionic/libc.so (abort+193) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
      #03 pc 01115f65  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #04 pc 0110443b  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #05 pc 01102202  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #06 pc 011622ad  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #07 pc 01114729  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #08 pc 01116ce8  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #09 pc 01116c2a  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #10 pc 0111d678  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #11 pc 0111d6a6  /data/app/com.ko2ic.fluttergoogleadmanagerexample-Qmv7dpbdceG5NS8Qq8u7ig==/lib/x86/libflutter.so (BuildId: 7ca566457ac4b7d6)
      #12 pc 00018487  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #13 pc 00019414  /system/lib/libutils.so (android::Looper::pollInner(int)+1044) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #14 pc 00018f4e  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+62) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #15 pc 0013299b  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #16 pc 002b86f8  /system/framework/x86/boot-framework.oat (art_jni_trampoline+136) (BuildId: ff6ec03dd8445d20788424c92ba8ea28ad0f54f4)
      #17 pc 02013466  /memfd:/jit-cache (deleted) (android.os.MessageQueue.next+230)
      #18 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #19 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #20 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #21 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #22 pc 0068186d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+989) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #23 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #24 pc 00319d8a  /system/framework/framework.jar (android.os.Looper.loop+130)
      #25 pc 00684f6c  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+1260) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #26 pc 001389a1  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+33) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #27 pc 0018945e  /system/framework/framework.jar (android.app.ActivityThread.main+194)
      #28 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6689468213397061768+298) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #29 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #30 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #31 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #32 pc 0013e9a2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #33 pc 00149a7a  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+298) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #34 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #35 pc 0055c32f  /apex/com.android.runtime/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1327) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #36 pc 004c9153  /apex/com.android.runtime/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+83) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #37 pc 000c6bf8  /system/framework/x86/boot.oat (art_jni_trampoline+168) (BuildId: 7913dbaef2e8d9971cb7619ef0d566987f8326a7)
      #38 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #39 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #40 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #41 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #42 pc 0068186d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+989) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #43 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #44 pc 0034cd36  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #45 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.6689468213397061768+298) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #46 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #47 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #48 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #49 pc 00998b08  /system/framework/x86/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1816) (BuildId: ff6ec03dd8445d20788424c92ba8ea28ad0f54f4)
      #50 pc 0013e9a2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #51 pc 00149a7a  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+298) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #52 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #53 pc 0055a1ae  /apex/com.android.runtime/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+430) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #54 pc 004305cd  /apex/com.android.runtime/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+893) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #55 pc 003d93bf  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+2847) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #56 pc 003c7509  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+73) (BuildId: a0a062684495092d1756e30ba2dff37d)
      #57 pc 000b25fe  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+62) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #58 pc 000b628a  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+794) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #59 pc 00003632  /system/bin/app_process32 (main+1490) (BuildId: b7a60bc7d078521421fd5a8d201915ae)
      #60 pc 000898e8  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+120) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
Lost connection to device.

```

**Comment by atrope** [comment]
Same Here, on Hot reload the app is killed.

**Comment by atrope** [comment]
@ko2ic are you planning on supporting this extension?
